# Generated by Django 2.2.4 on 2020-07-17 17:04

import api.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Último Login')),
                ('email', models.CharField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Senha')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Título')),
                ('level', models.CharField(max_length=20, validators=[api.models.validate_level], verbose_name='Nível')),
                ('address', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv4_address], verbose_name='Endereço IP')),
                ('date_event', models.DateTimeField(auto_now=True, verbose_name='Data do log')),
                ('detail', models.CharField(max_length=500, verbose_name='Detalhe')),
                ('arquivado', models.BooleanField(verbose_name='Arquivado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
    ]
